### ISSUE TITLE
Postgre version not loading

### ISSUE THREAD

**Issue by inigohidalgo** [gerardrbentley/streamlit-fullstack#1]
I was checking out your repo as I am considering using streamlit for some projects and wanted some inspiration. I just wanted to let you know that https://streamlit-postgres.gerardbentley.com/ isn't loading for me across various browsers due to ERR_CERT_INVALID, though the other two are loading just fine!

**Comment by gerardrbentley** [comment]
Slipped my mind after i was saving some space on the vps, should be back up, ty!
